services:
#    app_module_notebook_module_notebook_api.example:
#        class: App\ModuleNotebook\Bundle\ModuleNotebookApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
