services:
    app_module_notebook.repository.notebook:
        class: AppCommon\CommonModelBundle\Repository\BaseDoctrineEntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ App\ModuleNotebook\Bundle\ModuleNotebookBundle\Entity\Notebook ]
    
    app_module_notebook.repository.note:
        class: AppCommon\CommonModelBundle\Repository\BaseDoctrineEntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ App\ModuleNotebook\Bundle\ModuleNotebookBundle\Entity\Note ]
    
    app_module_notebook.repository.noteTag:
        class: AppCommon\CommonModelBundle\Repository\BaseDoctrineEntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [ App\ModuleNotebook\Bundle\ModuleNotebookBundle\Entity\NoteTag ]
