imports:
    - { resource: forms.yml }

services:
#    app_module_notebook_module_notebook_ui.example:
#        class: App\ModuleNotebook\Bundle\ModuleNotebookUiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
